<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\OnlyRag.Application\OnlyRag.Application.csproj" />
    <ProjectReference Include="..\OnlyRag.Core\OnlyRag.Core.csproj" />
    <ProjectReference Include="..\OnlyRag.Infrastructure\OnlyRag.Infrastructure.csproj" />
    <ProjectReference Include="..\OnlyRag.Infrastructure.Retrieval\OnlyRag.Infrastructure.Retrieval.csproj" />
    <ProjectReference Include="..\OnlyRag.Infrastructure.Storage\OnlyRag.Infrastructure.Storage.csproj" />
    <ProjectReference Include="..\OnlyRag.Jobs.Abstractions\OnlyRag.Jobs.Abstractions.csproj" />
  </ItemGroup>



  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.AI" Version="10.8.3" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
    <PackageReference Include="Microsoft.OpenApi" Version="2.11.0" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
