namespace OnlyRag.Core;

public sealed record OcrLanguage(string Code, string Label, string ScriptGroup, bool IsDefault = false);

public static class OcrLanguages
{
    public const string DefaultCode = "it";

    public static IReadOnlyList<OcrLanguage> All { get; } =
    [
        new("it", "Italiano", "Principali", IsDefault: true),
        new("en", "Inglese", "Principali"),
        new("fr", "Francese", "Principali"),
        new("de", "Tedesco", "Principali"),
        new("es", "Spagnolo", "Principali"),
        new("pt", "Portoghese", "Principali"),
        new("nl", "Olandese", "Principali"),
        new("pl", "Polacco", "Principali"),
        new("ro", "Rumeno", "Principali"),
        new("sv", "Svedese", "Principali"),
        new("da", "Danese", "Principali"),
        new("no", "Norvegese", "Principali"),
        new("fi", "Finlandese", "Principali"),
        new("cs", "Ceco", "Principali"),
        new("sk", "Slovacco", "Principali"),
        new("sl", "Sloveno", "Principali"),
        new("hr", "Croato", "Principali"),
        new("bs", "Bosniaco", "Principali"),
        new("hu", "Ungherese", "Principali"),
        new("tr", "Turco", "Principali"),
        new("el", "Greco", "Principali"),
        new("ru", "Russo", "Principali"),
        new("uk", "Ucraino", "Principali"),
        new("be", "Bielorusso", "Principali"),
        new("bg", "Bulgaro", "Principali"),
        new("rs_latin", "Serbo latino", "Principali"),
        new("rs_cyrillic", "Serbo cirillico", "Principali"),
        new("ar", "Arabo", "Principali"),
        new("fa", "Persiano", "Principali"),
        new("ur", "Urdu", "Principali"),
        new("hi", "Hindi", "Principali"),
        new("ta", "Tamil", "Principali"),
        new("te", "Telugu", "Principali"),
        new("th", "Thai", "Principali"),
        new("vi", "Vietnamita", "Principali"),
        new("id", "Indonesiano", "Principali"),
        new("ms", "Malese", "Principali"),
        new("ch", "Cinese semplificato + inglese", "Principali"),
        new("chinese_cht", "Cinese tradizionale", "Principali"),
        new("japan", "Giapponese", "Principali"),
        new("korean", "Coreano", "Principali"),
        new("af", "af", "Avanzate"),
        new("sq", "sq", "Avanzate"),
        new("az", "az", "Avanzate"),
        new("eu", "eu", "Avanzate"),
        new("ca", "ca", "Avanzate"),
        new("cy", "cy", "Avanzate"),
        new("et", "et", "Avanzate"),
        new("ga", "ga", "Avanzate"),
        new("gl", "gl", "Avanzate"),
        new("is", "is", "Avanzate"),
        new("la", "la", "Avanzate"),
        new("lt", "lt", "Avanzate"),
        new("lv", "lv", "Avanzate"),
        new("lb", "lb", "Avanzate"),
        new("mt", "mt", "Avanzate"),
        new("mi", "mi", "Avanzate"),
        new("oc", "oc", "Avanzate"),
        new("qu", "qu", "Avanzate"),
        new("rm", "rm", "Avanzate"),
        new("sw", "sw", "Avanzate"),
        new("tl", "tl", "Avanzate"),
        new("uz", "uz", "Avanzate"),
        new("kk", "kk", "Avanzate"),
        new("ky", "ky", "Avanzate"),
        new("tg", "tg", "Avanzate"),
        new("tt", "tt", "Avanzate"),
        new("mn", "mn", "Avanzate"),
        new("mk", "mk", "Avanzate"),
        new("cv", "cv", "Avanzate"),
        new("ba", "ba", "Avanzate"),
        new("mhr", "mhr", "Avanzate"),
        new("mo", "mo", "Avanzate"),
        new("udm", "udm", "Avanzate"),
        new("kv", "kv", "Avanzate"),
        new("os", "os", "Avanzate"),
        new("bua", "bua", "Avanzate"),
        new("xal", "xal", "Avanzate"),
        new("tyv", "tyv", "Avanzate"),
        new("sah", "sah", "Avanzate"),
        new("kaa", "kaa", "Avanzate"),
        new("ug", "ug", "Avanzate"),
        new("ps", "ps", "Avanzate"),
        new("sd", "sd", "Avanzate"),
        new("bal", "bal", "Avanzate"),
        new("mr", "mr", "Avanzate"),
        new("ne", "ne", "Avanzate"),
        new("bh", "bh", "Avanzate"),
        new("mai", "mai", "Avanzate"),
        new("ang", "ang", "Avanzate"),
        new("bho", "bho", "Avanzate"),
        new("mah", "mah", "Avanzate"),
        new("sck", "sck", "Avanzate"),
        new("new", "new", "Avanzate"),
        new("gom", "gom", "Avanzate"),
        new("sa", "sa", "Avanzate"),
        new("bgc", "bgc", "Avanzate"),
        new("ab", "ab", "Avanzate"),
        new("ady", "ady", "Avanzate"),
        new("kbd", "kbd", "Avanzate"),
        new("av", "av", "Avanzate"),
        new("dar", "dar", "Avanzate"),
        new("inh", "inh", "Avanzate"),
        new("ce", "ce", "Avanzate"),
        new("lki", "lki", "Avanzate"),
        new("lez", "lez", "Avanzate"),
        new("tab", "tab", "Avanzate")
    ];

    public static string NormalizeCode(string? code)
    {
        string normalized = string.IsNullOrWhiteSpace(code)
            ? DefaultCode
            : code.Trim();

        return All.FirstOrDefault(language => string.Equals(language.Code, normalized, StringComparison.OrdinalIgnoreCase))?.Code
            ?? DefaultCode;
    }
}
