namespace OnlyRag.Core;

public sealed record OcrLanguage(string Code, string Label, string ScriptGroup, bool IsDefault = false);

public static class OcrLanguages
{
    public const string DefaultCode = "it";

    public static IReadOnlyList<OcrLanguage> All { get; } =
    [
        new("it", "Italiano", "Principali", IsDefault: true),
        new("en", "Inglese", "Principali"),
        new("fr", "Francese", "Principali"),
        new("de", "Tedesco", "Principali"),
        new("es", "Spagnolo", "Principali"),
        new("pt", "Portoghese", "Principali"),
        new("nl", "Olandese", "Principali"),
        new("pl", "Polacco", "Principali"),
        new("ro", "Rumeno", "Principali"),
        new("sv", "Svedese", "Principali"),
        new("da", "Danese", "Principali"),
        new("no", "Norvegese", "Principali"),
        new("fi", "Finlandese", "Principali"),
        new("cs", "Ceco", "Principali"),
        new("sk", "Slovacco", "Principali"),
        new("sl", "Sloveno", "Principali"),
        new("hr", "Croato", "Principali"),
        new("bs", "Bosniaco", "Principali"),
        new("hu", "Ungherese", "Principali"),
        new("tr", "Turco", "Principali"),
        new("el", "Greco", "Principali"),
        new("ru", "Russo", "Principali"),
        new("uk", "Ucraino", "Principali"),
        new("be", "Bielorusso", "Principali"),
        new("bg", "Bulgaro", "Principali"),
        new("rs_latin", "Serbo latino", "Principali"),
        new("rs_cyrillic", "Serbo cirillico", "Principali"),
        new("ar", "Arabo", "Principali"),
        new("fa", "Persiano", "Principali"),
        new("ur", "Urdu", "Principali"),
        new("hi", "Hindi", "Principali"),
        new("ta", "Tamil", "Principali"),
        new("te", "Telugu", "Principali"),
        new("th", "Thai", "Principali"),
        new("vi", "Vietnamita", "Principali"),
        new("id", "Indonesiano", "Principali"),
        new("ms", "Malese", "Principali"),
        new("ch", "Cinese semplificato + inglese", "Principali"),
        new("chinese_cht", "Cinese tradizionale", "Principali"),
        new("japan", "Giapponese", "Principali"),
        new("korean", "Coreano", "Principali"),
        new("af", "Afrikaans", "Avanzate"),
        new("sq", "Albanese", "Avanzate"),
        new("az", "Azero", "Avanzate"),
        new("eu", "Basco", "Avanzate"),
        new("ca", "Catalano", "Avanzate"),
        new("cy", "Gallese", "Avanzate"),
        new("et", "Estone", "Avanzate"),
        new("ga", "Irlandese", "Avanzate"),
        new("gl", "Galiziano", "Avanzate"),
        new("is", "Islandese", "Avanzate"),
        new("la", "Latino", "Avanzate"),
        new("lt", "Lituano", "Avanzate"),
        new("lv", "Lettone", "Avanzate"),
        new("lb", "Lussemburghese", "Avanzate"),
        new("mt", "Maltese", "Avanzate"),
        new("mi", "Maori", "Avanzate"),
        new("oc", "Occitano", "Avanzate"),
        new("qu", "Quechua", "Avanzate"),
        new("rm", "Romancio", "Avanzate"),
        new("sw", "Swahili", "Avanzate"),
        new("tl", "Tagalog", "Avanzate"),
        new("uz", "Uzbeko", "Avanzate"),
        new("ku", "Curdo", "Avanzate"),
        new("pi", "Pali", "Avanzate"),
        new("kk", "Kazako", "Avanzate"),
        new("ky", "Kirghiso", "Avanzate"),
        new("tg", "Tagiko", "Avanzate"),
        new("tt", "Tataro", "Avanzate"),
        new("mn", "Mongolo", "Avanzate"),
        new("mk", "Macedone", "Avanzate"),
        new("cv", "Ciuvascio", "Avanzate"),
        new("ba", "Baschiro", "Avanzate"),
        new("mhr", "Mari", "Avanzate"),
        new("mo", "Moldavo", "Avanzate"),
        new("udm", "Udmurto", "Avanzate"),
        new("kv", "Komi", "Avanzate"),
        new("os", "Osseto", "Avanzate"),
        new("bua", "Buriato", "Avanzate"),
        new("xal", "Calmucco", "Avanzate"),
        new("tyv", "Tuvano", "Avanzate"),
        new("sah", "Sakha", "Avanzate"),
        new("kaa", "Karakalpako", "Avanzate"),
        new("ug", "Uiguro", "Avanzate"),
        new("ps", "Pashto", "Avanzate"),
        new("sd", "Sindhi", "Avanzate"),
        new("bal", "Baloci", "Avanzate"),
        new("mr", "Marathi", "Avanzate"),
        new("ne", "Nepalese", "Avanzate"),
        new("bh", "Bihari", "Avanzate"),
        new("mai", "Maithili", "Avanzate"),
        new("ang", "Inglese antico", "Avanzate"),
        new("bho", "Bhojpuri", "Avanzate"),
        new("mah", "Magahi", "Avanzate"),
        new("sck", "Sadri", "Avanzate"),
        new("new", "Newar", "Avanzate"),
        new("gom", "Konkani", "Avanzate"),
        new("sa", "Sanscrito", "Avanzate"),
        new("bgc", "Haryanvi", "Avanzate"),
        new("ab", "Abkhazo", "Avanzate"),
        new("ady", "Adighè", "Avanzate"),
        new("kbd", "Cabardino", "Avanzate"),
        new("av", "Avaro", "Avanzate"),
        new("dar", "Dargwa", "Avanzate"),
        new("inh", "Inguscio", "Avanzate"),
        new("ce", "Ceceno", "Avanzate"),
        new("lki", "Lak", "Avanzate"),
        new("lez", "Lezgino", "Avanzate"),
        new("tab", "Tabasarano", "Avanzate")
    ];

    public static string NormalizeCode(string? code)
    {
        string normalized = string.IsNullOrWhiteSpace(code)
            ? DefaultCode
            : code.Trim();

        return All.FirstOrDefault(language => string.Equals(language.Code, normalized, StringComparison.OrdinalIgnoreCase))?.Code
            ?? DefaultCode;
    }
}
